---
version: '3.8'

x-rpmbuild:
  dist: &rpmbuild_dist '.el7'
  channel_name: &rpmbuild_channel stable
  email: &rpmbuild_email "foundationgeoint-packaging@maxar.com"
  packager_name: &rpmbuild_name "FoundationGEOINT Packaging"
  postgres_version: &postgres_version '13'
  vendor: &rpmbuild_vendor "Maxar Technologies"
  base_args: &rpmbuild_base_args
    rpmbuild_dist: *rpmbuild_dist
    rpmbuild_email: *rpmbuild_email
    rpmbuild_name: *rpmbuild_name
    rpmbuild_uid: "${RPMBUILD_UID}"
    rpmbuild_gid: "${RPMBUILD_GID}"
  build_defaults: &build_defaults
    context: .
    dockerfile: docker/Dockerfile.rpmbuild-generic
    labels:
      maintainer: *rpmbuild_email
      vendor: *rpmbuild_vendor
  # Configuration for every dependency RPM.
  rpms:
    CGAL:
      image: &CGAL_image rpmbuild-cgal
      version: &CGAL_version '4.14.3-1'
    FileGDBAPI:
      image: &FileGDBAPI_image rpmbuild-generic
      version: &FileGDBAPI_version '1.5.1-1'
    SFCGAL:
      image: &SFCGAL_image rpmbuild-sfcgal
      version: &SFCGAL_version '1.3.9-1'
    gdal:
      image: &gdal_image rpmbuild-gdal
      version: &gdal_version '3.2.1-1'
    geos:
      image: &geos_image rpmbuild-geos
      version: &geos_version '3.9.1-1'
    gpsbabel:
      image: &gpsbabel_image rpmbuild-gpsbabel
      version: &gpsbabel_version '1.7.0-1'
    libgeotiff:
      image: &libgeotiff_image rpmbuild-libgeotiff
      version: &libgeotiff_version '1.6.0-1'
    libkml:
      image: &libkml_image rpmbuild-libkml
      version: &libkml_version '1.3.0-1'
    libosmium:
      image: &libosmium_image rpmbuild-libosmium
      version: &libosmium_version '2.16.0-1'
      arch: noarch
      name: libosmium-devel
    osmosis:
      image: &osmosis_image rpmbuild-generic
      version: &osmosis_version '0.48.3-1'
      arch: noarch
    osmium-tool:
      image: &osmium-tool_image rpmbuild-osmium-tool
      version: &osmium-tool_version '1.13.1-1'
    sbt:
      image: &sbt_image rpmbuild-generic
      version: &sbt_version '1.4.7-1'
      arch: noarch
    postgis:
      image: &postgis_image rpmbuild-postgis
      version: &postgis_version '3.1.1-1'
    proj:
      image: &proj_image rpmbuild-proj
      version: &proj_version '7.2.1-1'
    proj6:
      image: &proj6_image rpmbuild-proj
      version: &proj6_version '6.3.2-1'
      name: proj
    protobuf:
      image: &protobuf_image rpmbuild-protobuf
      version: &protobuf_version '3.15.1-1'
    protobuf-c:
      image: &protobuf-c_image rpmbuild-protobuf-c
      version: &protobuf-c_version '1.3.3-1'
    protozero:
      image: &protozero_image rpmbuild-protozero
      version: &protozero_version '1.7.0-1'
      arch: noarch
      name: protozero-devel
    ruby:
      image: &ruby_image rpmbuild-ruby
      version: &ruby_version '2.7.2-1'
      defines:
        bundler_version: '2.1.4'
        bundler_connection_pool_version: '2.2.2'
        bundler_fileutils_version: '1.3.0'
        bundler_molinillo_version: '0.6.6'
        bundler_net_http_persistent_version: '3.1.0'
        bundler_thor_version: '1.0.0'
        bigdecimal_version: '2.0.0'
        did_you_mean_version: '1.4.0'
        io_console_version: '0.5.6'
        irb_version: '1.2.6'
        json_version: '2.3.0'
        minitest_version: '5.13.0'
        net_telnet_version: '0.2.0'
        openssl_version: '2.1.2'
        power_assert_version: '1.1.7'
        psych_version: '3.1.0'
        racc_version: '1.4.16'
        rake_version: '13.0.1'
        rdoc_version: '6.2.1'
        rubygems_version: '3.1.4'
        rubygems_molinillo_version: '0.5.7'
        test_unit_version: '3.3.4'
        xmlrpc_version: '0.3.0'
    sqlite:
      image: &sqlite_image rpmbuild-sqlite
      version: &sqlite_version '3.34.1-1'
  service_volumes: &service_volumes
    - "./RPMS:/rpmbuild/RPMS:rw"
    - "./SOURCES:/rpmbuild/SOURCES:rw"
    - "./SPECS:/rpmbuild/SPECS:ro"
    - "./scripts:/rpmbuild/scripts:ro"
  service_defaults: &service_defaults
    command: 'tail -f /dev/null'
    init: true
    volumes: *service_volumes

services:
  rpmbuild:
    build:
      context: .
      dockerfile: docker/Dockerfile.rpmbuild
      args:
        <<: *rpmbuild_base_args
      labels:
        maintainer: *rpmbuild_email
        vendor: *rpmbuild_vendor
    command: 'tail -f /dev/null'
    init: true
    user: nobody
  rpmbuild-generic:
    <<: *service_defaults
    depends_on:
      - rpmbuild
    build:
      <<: *build_defaults
      args:
        rpmbuild_channel: *rpmbuild_channel
  rpmbuild-cgal:
    <<: *service_defaults
    depends_on:
      - rpmbuild-generic
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_CGAL_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
  rpmbuild-gdal:
    <<: *service_defaults
    depends_on:
      - rpmbuild-pgdg
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_GDAL_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
        cgal_version: *CGAL_version
        filegdbapi_version: *FileGDBAPI_version
        geos_version: *geos_version
        gpsbabel_version: *gpsbabel_version
        libgeotiff_version: *libgeotiff_version
        libkml_version: *libkml_version
        proj_version: *proj_version
        sfcgal_version: *SFCGAL_version
        sqlite_version: *sqlite_version
      dockerfile: docker/Dockerfile.rpmbuild-gdal
  rpmbuild-geos:
    <<: *service_defaults
    depends_on:
      - rpmbuild-generic
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_GEOS_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
  rpmbuild-gpsbabel:
    <<: *service_defaults
    depends_on:
      - rpmbuild-generic
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_GPSBABEL_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
  rpmbuild-proj:
    <<: *service_defaults
    depends_on:
      - rpmbuild-sqlite
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_PROJ_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
        sqlite_version: *sqlite_version
      dockerfile: docker/Dockerfile.rpmbuild-proj
  rpmbuild-protobuf:
    <<: *service_defaults
    depends_on:
      - rpmbuild-generic
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_PROTOBUF_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
  rpmbuild-protobuf-c:
    <<: *service_defaults
    depends_on:
      - rpmbuild-protobuf
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_PROTOBUF_C_PACKAGES}"
        protobuf_version: *protobuf_version
        rpmbuild_channel: *rpmbuild_channel
      dockerfile: docker/Dockerfile.rpmbuild-protobuf-c
  rpmbuild-libgeotiff:
    <<: *service_defaults
    depends_on:
      - rpmbuild-proj
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_LIBGEOTIFF_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
        proj_version: *proj_version
      dockerfile: docker/Dockerfile.rpmbuild-libgeotiff
  rpmbuild-libkml:
    <<: *service_defaults
    depends_on:
      - rpmbuild-generic
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_LIBKML_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
  rpmbuild-libosmium:
    <<: *service_defaults
    depends_on:
      - rpmbuild-protozero
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_LIBOSMIUM_PACKAGES}"
        protozero_version: *protozero_version
        rpmbuild_channel: *rpmbuild_channel
      dockerfile: docker/Dockerfile.rpmbuild-libosmium
  rpmbuild-osmium-tool:
    <<: *service_defaults
    depends_on:
      - rpmbuild-libosmium
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_OSMIUM_TOOL_PACKAGES}"
        protozero_version: *protozero_version
        libosmium_version: *libosmium_version
        rpmbuild_channel: *rpmbuild_channel
      dockerfile: docker/Dockerfile.rpmbuild-osmium-tool
  rpmbuild-pgdg:
    <<: *service_defaults
    depends_on:
      - rpmbuild
    build:
      <<: *build_defaults
      args:
        postgres_version: *postgres_version
        rpmbuild_channel: *rpmbuild_channel
      dockerfile: docker/Dockerfile.rpmbuild-pgdg
  rpmbuild-postgis:
    <<: *service_defaults
    depends_on:
      - rpmbuild-gdal
      - rpmbuild-protobuf-c
    build:
      <<: *build_defaults
      args:
        cgal_version: *CGAL_version
        filegdbapi_version: *FileGDBAPI_version
        gdal_version: *gdal_version
        geos_version: *geos_version
        gpsbabel_version: *gpsbabel_version
        libgeotiff_version: *libgeotiff_version
        libkml_version: *libkml_version
        packages: "${RPMBUILD_POSTGIS_PACKAGES}"
        proj_version: *proj_version
        protobuf_version: *protobuf_version
        protobuf_c_version: *protobuf-c_version
        rpmbuild_channel: *rpmbuild_channel
        sfcgal_version: *SFCGAL_version
        sqlite_version: *sqlite_version
      dockerfile: docker/Dockerfile.rpmbuild-postgis
  rpmbuild-protozero:
    <<: *service_defaults
    depends_on:
      - rpmbuild-protobuf
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_PROTOZERO_PACKAGES}"
        protobuf_version: *protobuf_version
        rpmbuild_channel: *rpmbuild_channel
      dockerfile: docker/Dockerfile.rpmbuild-protozero
  rpmbuild-ruby:
    <<: *service_defaults
    depends_on:
      - rpmbuild-generic
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_RUBY_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
  rpmbuild-sfcgal:
    <<: *service_defaults
    depends_on:
      - rpmbuild-cgal
    build:
      <<: *build_defaults
      args:
        cgal_version: *CGAL_version
        packages: "${RPMBUILD_SFCGAL_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
      dockerfile: docker/Dockerfile.rpmbuild-sfcgal
  rpmbuild-sqlite:
    <<: *service_defaults
    depends_on:
      - rpmbuild-generic
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_SQLITE_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
