---
version: '3.8'

x-channel:
  dist: &rpmbuild_dist '.el7'
  channel_name: &rpmbuild_channel stable
  email: &rpmbuild_email "foundation-geoint-packaging@maxar.com"
  packager_name: &rpmbuild_name "Foundation Geoint Packaging"
  postgres_version:  &postgres_version '10'
  vendor: &rpmbuild_vendor "Maxar Technologies"

x-build-args: &rpmbuild_build_args
  rpmbuild_dist: *rpmbuild_dist
  rpmbuild_email: *rpmbuild_email
  rpmbuild_name: *rpmbuild_name

x-build-labels: &rpmbuild_build_labels
  maintainer: *rpmbuild_email
  vendor: *rpmbuild_vendor

x-versions:
  osmosis: &osmosis_version '0.48.3-1'
  sbt: &sbt_version '1.3.8-1'
  sqlite: &sqlite_version '3.34.1-1'

x-volumes: &rpmbuild_volumes
  - "./RPMS:/rpmbuild/RPMS:rw"
  - "./SOURCES:/rpmbuild/SOURCES:rw"
  - "./SPECS:/rpmbuild/SPECS:ro"
  - "./scripts:/rpmbuild/scripts:ro"


## Docker Compose
services:
  rpmbuild:
    build:
      context: .
      dockerfile: docker/Dockerfile.rpmbuild
      args:
        <<: *rpmbuild_build_args
        rpmbuild_uid: "${RPMBUILD_UID}"
        rpmbuild_gid: "${RPMBUILD_GID}"
      labels:
        <<: *rpmbuild_build_labels
    command: 'tail -f /dev/null'
    init: true
    volumes: *rpmbuild_volumes
  rpmbuild-generic:
    build:
      context: .
      dockerfile: docker/Dockerfile.rpmbuild-generic
      args:
        rpmbuild_channel: *rpmbuild_channel
      labels:
        <<: *rpmbuild_build_labels
    command: 'tail -f /dev/null'
    depends_on:
      - rpmbuild
    init: true
    volumes: *rpmbuild_volumes


## Vagrant
x-vagrant:
  images:
    base: !!omap
      - rpmbuild:
          args: *rpmbuild_build_args
      - rpmbuild-generic:
          args:
            rpmbuild_channel: *rpmbuild_channel
  rpms:
    osmosis:
      image: rpmbuild-generic
      version: *osmosis_version
    sbt:
      image: rpmbuild-generic
      version: *sbt_version
    sqlite:
      image: rpmbuild-generic
      version: *sqlite_version
