---
version: "3.7"

x-rpmbuild:
  channel_name: &rpmbuild_channel stable
  dist: &rpmbuild_dist .el7
  email: &rpmbuild_email foundationgeoint-packaging@maxar.com
  image_prefix: &rpmbuild_image_prefix ${IMAGE_PREFIX}
  packager_name: &rpmbuild_name FoundationGEOINT Packaging
  postgres_version: &postgres_version "13"
  vendor: &rpmbuild_vendor Maxar Technologies
  base_args: &rpmbuild_base_args
    rpmbuild_dist: *rpmbuild_dist
    rpmbuild_email: *rpmbuild_email
    rpmbuild_gid: ${RPMBUILD_GID}
    rpmbuild_name: *rpmbuild_name
    rpmbuild_uid: ${RPMBUILD_UID}
  build_defaults: &build_defaults
    context: .
    dockerfile: docker/el7/Dockerfile.rpmbuild-generic
    labels:
      maintainer: *rpmbuild_email
      vendor: *rpmbuild_vendor
  build_args_defaults: &build_args_defaults
    rpmbuild_channel: *rpmbuild_channel
    rpmbuild_image_prefix: *rpmbuild_image_prefix
    rpmbuild_image: rpmbuild
  # Use consistent values for minimum versions for RPM build
  # and runtime requirements.
  minimum_versions:
    gdal: &gdal_min_version 3.8.0
    geos: &geos_min_version 3.11.0
    libosmium: &libosmium_min_version 2.18.0
    postgis_min_version: &postgis_min_version 3.1.0
    proj: &proj_min_version 7.2.0
    protobuf-c: &protobuf_c_min_version 1.3.0
    protobuf: &protobuf_min_version 3.0.0
    protozero: &protozero_min_version 1.7.0
    sqlite_min_version: &sqlite_min_version 3.11.0
  # Configuration for building every dependency RPM.
  rpms:
    CGAL:
      image: rpmbuild-cgal
      version: &CGAL_version 4.14.3-2
    FileGDBAPI:
      image: rpmbuild-generic
      version: &FileGDBAPI_version 1.5.2-1
    SFCGAL:
      image: rpmbuild-sfcgal
      version: &SFCGAL_version 1.3.10-1
    caddy:
      image: rpmbuild-caddy
      version: &caddy_version 2.7.5-1
    dumb-init:
      image: rpmbuild-generic
      version: 1.2.5-1
    gdal:
      image: rpmbuild-gdal
      version: &gdal_version 3.8.0-1
      defines:
        geos_min_version: 3.11.0
        proj_min_version: *proj_min_version
    geos:
      image: rpmbuild-generic
      version: &geos_version 3.11.3-1
    gpsbabel:
      image: rpmbuild-gpsbabel
      version: &gpsbabel_version 1.7.0-1
    google-noto-fonts-extra:
      image: rpmbuild-fonts
      version: &google-noto-fonts-extra_version 20220418-1
      defines:
        commit: 523a250c35d417c217c580f0743e41d8ca4b7657
      arch: noarch
    hanazono-fonts:
      image: rpmbuild-fonts
      version: &hanazono-fonts_version 20170904-1
      arch: noarch
    libgeotiff:
      image: rpmbuild-libgeotiff
      version: &libgeotiff_version 1.7.1-1
      defines:
        proj_min_version: *proj_min_version
    journald-cloudwatch-logs:
      image: rpmbuild-journald-cloudwatch-logs
      version: &journald-cloudwatch-logs_version 0.2.3-1
    libkml:
      image: rpmbuild-libkml
      version: &libkml_version 1.3.0-1
    libosmium:
      image: rpmbuild-libosmium
      version: &libosmium_version 2.20.0-1
      arch: noarch
      name: libosmium-devel
      defines:
        protozero_min_version: *protozero_min_version
    libosmpbf:
      image: rpmbuild-libosmpbf
      version: &libosmpbf_version 1.5.0-1
      defines:
        protobuf_min_version: *protobuf_min_version
    mapnik:
      image: rpmbuild-mapnik
      version: &mapnik_version 3.0.24-2
      defines:
        geos_min_version: *geos_min_version
        postgis_min_version: *postgis_min_version
        proj_min_version: *proj_min_version
    ogdi:
      image: rpmbuild-ogdi
      version: &ogdi_version 4.1.0-1
    openstreetmap-carto:
      image: rpmbuild-openstreetmap-carto
      version: &openstreetmap_carto_version 5.4.0-4
      arch: noarch
      defines:
        data_natural_earth_version: 5.1.0
    osmctools:
      image: rpmbuild-osmctools
      version: &osmctools_version 0.9-1
    osmdbt:
      image: rpmbuild-osmdbt
      version: &osmdbt_version 0.3-1
      defines:
        commit: e0158c0751207b0e77ab67e40a837016759e203d
        libosmium_min_version: *libosmium_min_version
    osmosis:
      image: rpmbuild-generic
      version: &osmosis_version 0.48.3-1
      arch: noarch
    osmium-tool:
      image: rpmbuild-osmium-tool
      version: &osmium-tool_version 1.16.0-1
      defines:
        libosmium_min_version: *libosmium_min_version
        protozero_min_version: *protozero_min_version
    osm2pgsql:
      image: rpmbuild-osm2pgsql
      version: &osm2pgsql_version 1.10.0-1
      defines:
        libosmium_min_version: *libosmium_min_version
        nlohmann_json_version: 3.11.2
        proj_min_version: *proj_min_version
        postgis_min_version: *postgis_min_version
        protobuf_c_min_version: *protobuf_c_min_version
    passenger:
      image: rpmbuild-passenger
      version: &passenger_version 6.0.18-1
    planet-dump-ng:
      image: rpmbuild-planet-dump-ng
      version: &planet_dump_ng_version 1.2.7-1
      defines:
        protobuf_min_version: *protobuf_min_version
    postgis:
      image: rpmbuild-postgis
      version: &postgis_version 3.3.5-1
      defines:
        gdal_min_version: *gdal_min_version
        geos_min_version: *geos_min_version
        proj_min_version: *proj_min_version
        protobuf_min_version: *protobuf_min_version
        protobuf_c_min_version: *protobuf_c_min_version
    proj:
      image: rpmbuild-proj
      version: &proj_version 7.2.1-1
      defines:
        data_version: 1.4
        googletest_version: 1.8.1
        sqlite_min_version: *sqlite_min_version
    protobuf:
      image: rpmbuild-protobuf
      version: &protobuf_version 3.17.3-1
    protobuf-c:
      image: rpmbuild-protobuf-c
      version: &protobuf-c_version 1.4.1-1
      defines:
        protobuf_min_version: *protobuf_min_version
    protozero:
      image: rpmbuild-protozero
      version: &protozero_version 1.7.1-1
      arch: noarch
      name: protozero-devel
      defines:
        protobuf_min_version: *protobuf_min_version
    python3-osmium:
      image: rpmbuild-pyosmium
      version: &pyosmium_version 3.6.0-1
      defines:
        libosmium_min_version: *libosmium_min_version
        protozero_min_version: *protozero_min_version
        pybind11_version: 2.10.3
    rack:
      image: rpmbuild-rack
      version: &rack_version 2.2.6.2-1
      arch: noarch
      name: rubygem-rack
      spec_file: SPECS/rubygem-rack.spec
    ruby:
      image: rpmbuild-ruby
      version: &ruby_version 2.7.8-1
      defines: &ruby_bundled_versions
        bundler_version: 2.1.4
        bundler_connection_pool_version: 2.2.2
        bundler_fileutils_version: 1.3.0
        bundler_molinillo_version: 0.6.6
        bundler_net_http_persistent_version: 3.1.0
        bundler_thor_version: 1.0.0
        bigdecimal_version: 2.0.0
        did_you_mean_version: 1.4.0
        io_console_version: 0.5.6
        irb_version: 1.2.6
        json_version: 2.3.0
        minitest_version: 5.13.0
        net_telnet_version: 0.2.0
        openssl_version: 2.1.4
        power_assert_version: 1.1.7
        psych_version: 3.1.0
        racc_version: 1.4.16
        rake_version: 13.0.1
        rdoc_version: 6.2.1.1
        rubygems_version: 3.1.6
        rubygems_molinillo_version: 0.5.7
        test_unit_version: 3.3.4
        xmlrpc_version: 0.3.0
    rubygem-pg:
      image: rpmbuild-rubygem-pg
      version: &rubygem_pg_version 1.3.5-1
    rubygem-libxml-ruby:
      image: rpmbuild-rubygem-libxml-ruby
      version: &rubygem_libxml_ruby_version 4.1.2-1
    sbt:
      image: rpmbuild-generic
      version: &sbt_version 1.9.7-1
      arch: noarch
    sqlite:
      image: rpmbuild-sqlite
      version: &sqlite_version 3.36.0-2
    sqlite-pcre:
      image: rpmbuild-sqlite-pcre
      version: &sqlite_pcre_version 2007.1.20-1
    step-ca:
      image: rpmbuild-smallstep
      version: &step_ca_version 0.25.0-1
    step-cli:
      image: rpmbuild-smallstep
      version: &step_cli_version 0.25.0-1
    tbb:
      image: rpmbuild-tbb
      version: &tbb_version 2020.3-1
    wal-g:
      image: rpmbuild-wal-g
      version: &walg_version 2.0.1-1
  service_volumes: &service_volumes
    - ./RPMS:/rpmbuild/RPMS:rw
    - ./SOURCES/el7:/rpmbuild/SOURCES:rw
    - ./SPECS/el7:/rpmbuild/SPECS:ro
    - ./scripts:/rpmbuild/scripts:ro
  service_defaults: &service_defaults
    command: tail -f /dev/null
    init: true
    volumes: *service_volumes

services:
  # Base images
  rpmbuild:
    build:
      context: .
      dockerfile: docker/el7/Dockerfile.rpmbuild
      args:
        <<: *rpmbuild_base_args
      labels:
        maintainer: *rpmbuild_email
        vendor: *rpmbuild_vendor
    command: tail -f /dev/null
    image: ${IMAGE_PREFIX}rpmbuild
    init: true
    user: nobody
  rpmbuild-fonts:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: fontpackages-devel
    image: ${IMAGE_PREFIX}rpmbuild-fonts
  rpmbuild-generic:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
    image: ${IMAGE_PREFIX}rpmbuild-generic
  rpmbuild-pgdg:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        postgres_version: *postgres_version
      dockerfile: docker/el7/Dockerfile.rpmbuild-pgdg
    image: ${IMAGE_PREFIX}rpmbuild-pgdg
  # RPM images
  rpmbuild-caddy:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        rpmbuild_image: rpmbuild-generic
      dockerfile: docker/el7/Dockerfile.rpmbuild-go
  rpmbuild-cgal:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_CGAL_PACKAGES}
  rpmbuild-gdal:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        cgal_version: *CGAL_version
        filegdbapi_version: *FileGDBAPI_version
        geos_version: *geos_version
        gpsbabel_version: *gpsbabel_version
        libgeotiff_version: *libgeotiff_version
        libkml_version: *libkml_version
        ogdi_version: *ogdi_version
        packages: ${RPMBUILD_GDAL_PACKAGES}
        proj_version: *proj_version
        rpmbuild_image: rpmbuild-pgdg
        sfcgal_version: *SFCGAL_version
        sqlite_version: *sqlite_version
      dockerfile: docker/el7/Dockerfile.rpmbuild-gdal
  rpmbuild-gpsbabel:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_GPSBABEL_PACKAGES}
  rpmbuild-proj:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_PROJ_PACKAGES}
        sqlite_version: *sqlite_version
      dockerfile: docker/el7/Dockerfile.rpmbuild-proj
  rpmbuild-protobuf:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_PROTOBUF_PACKAGES}
  rpmbuild-protobuf-c:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_PROTOBUF_C_PACKAGES}
        protobuf_version: *protobuf_version
      dockerfile: docker/el7/Dockerfile.rpmbuild-protobuf-c
  rpmbuild-libgeotiff:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_LIBGEOTIFF_PACKAGES}
        proj_version: *proj_version
        sqlite_version: *sqlite_version
      dockerfile: docker/el7/Dockerfile.rpmbuild-libgeotiff
  rpmbuild-libkml:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_LIBKML_PACKAGES}
  rpmbuild-libosmium:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_LIBOSMIUM_PACKAGES}
        protozero_version: *protozero_version
      dockerfile: docker/el7/Dockerfile.rpmbuild-libosmium
  rpmbuild-libosmpbf:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_LIBOSMPBF_PACKAGES}
      dockerfile: docker/el7/Dockerfile.rpmbuild-geoint-deps
  rpmbuild-journald-cloudwatch-logs:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_JOURNALD_CLOUDWATCH_LOGS_PACKAGES}
        rpmbuild_image: rpmbuild-generic
      dockerfile: docker/el7/Dockerfile.rpmbuild-go
  rpmbuild-mapnik:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_MAPNIK_PACKAGES}
        rpmbuild_image: rpmbuild-pgdg
      dockerfile: docker/el7/Dockerfile.rpmbuild-geoint-pgdg
  rpmbuild-ogdi:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_OGDI_PACKAGES}
      dockerfile: docker/el7/Dockerfile.rpmbuild-geoint-deps
  rpmbuild-openstreetmap-carto:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_OPENSTREETMAP_CARTO_PACKAGES}
  rpmbuild-osmctools:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_OSMCTOOLS_PACKAGES}
  rpmbuild-osmdbt:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_OSMDBT_PACKAGES}
        rpmbuild_image: rpmbuild-pgdg
      dockerfile: docker/el7/Dockerfile.rpmbuild-geoint-pgdg
  rpmbuild-osmium-tool:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_OSMIUM_TOOL_PACKAGES}
      dockerfile: docker/el7/Dockerfile.rpmbuild-geoint-deps
  rpmbuild-osm2pgsql:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_OSM2PGSQL_PACKAGES}
        rpmbuild_image: rpmbuild-pgdg
      dockerfile: docker/el7/Dockerfile.rpmbuild-geoint-pgdg
  rpmbuild-passenger:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_PASSENGER_PACKAGES}
      dockerfile: docker/el7/Dockerfile.rpmbuild-geoint-deps
  rpmbuild-planet-dump-ng:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_PLANET_DUMP_NG_PACKAGES}
      dockerfile: docker/el7/Dockerfile.rpmbuild-geoint-deps
  rpmbuild-postgis:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_POSTGIS_PACKAGES}
        rpmbuild_image: rpmbuild-pgdg
      dockerfile: docker/el7/Dockerfile.rpmbuild-geoint-pgdg
  rpmbuild-protozero:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_PROTOZERO_PACKAGES}
        protobuf_version: *protobuf_version
      dockerfile: docker/el7/Dockerfile.rpmbuild-protozero
  rpmbuild-pyosmium:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_PYOSMIUM_PACKAGES}
        python_packages: pytest==7.0.1
      dockerfile: docker/el7/Dockerfile.rpmbuild-geoint-deps
  rpmbuild-rack:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        gem_packages: >-
          minitest
          minitest-global_expectations
          minitest-sprint
          webrick
        packages: ${RPMBUILD_RACK_PACKAGES}
      dockerfile: docker/el7/Dockerfile.rpmbuild-geoint-deps
  rpmbuild-ruby:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_RUBY_PACKAGES}
  rpmbuild-rubygem-libxml-ruby:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        gem_packages: >-
          minitest
          rake-compiler
        packages: ${RPMBUILD_RUBYGEM_LIBXML_RUBY_PACKAGES}
      dockerfile: docker/el7/Dockerfile.rpmbuild-geoint-deps
  rpmbuild-rubygem-pg:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        gem_packages: >-
          hoe
          rake-compiler
          rspec
        packages: ${RPMBUILD_RUBYGEM_PG_PACKAGES}
        postgres_version: *postgres_version
        rpmbuild_image: rpmbuild-pgdg
      dockerfile: docker/el7/Dockerfile.rpmbuild-geoint-pgdg
  rpmbuild-sfcgal:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        cgal_version: *CGAL_version
        packages: ${RPMBUILD_SFCGAL_PACKAGES}
      dockerfile: docker/el7/Dockerfile.rpmbuild-sfcgal
  rpmbuild-sqlite:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_SQLITE_PACKAGES}
  rpmbuild-sqlite-pcre:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_SQLITE_PCRE_PACKAGES}
        sqlite_version: *sqlite_version
      dockerfile: docker/el7/Dockerfile.rpmbuild-proj
  rpmbuild-smallstep:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_STEP_CA_PACKAGES}
        rpmbuild_image: rpmbuild-generic
      dockerfile: docker/el7/Dockerfile.rpmbuild-go
  rpmbuild-tbb:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_TBB_PACKAGES}
  rpmbuild-wal-g:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_WALG_PACKAGES}
        rpmbuild_image: rpmbuild-generic
      dockerfile: docker/el7/Dockerfile.rpmbuild-go
