---
version: '3.8'

x-rpmbuild:
  dist: &rpmbuild_dist '.el7'
  channel_name: &rpmbuild_channel stable
  email: &rpmbuild_email "foundationgeoint-packaging@maxar.com"
  packager_name: &rpmbuild_name "FoundationGEOINT Packaging"
  postgres_version: &postgres_version '13'
  vendor: &rpmbuild_vendor "Maxar Technologies"
  base_args: &rpmbuild_base_args
    rpmbuild_dist: *rpmbuild_dist
    rpmbuild_email: *rpmbuild_email
    rpmbuild_name: *rpmbuild_name
    rpmbuild_uid: "${RPMBUILD_UID}"
    rpmbuild_gid: "${RPMBUILD_GID}"
  build_defaults: &build_defaults
    context: .
    dockerfile: docker/Dockerfile.rpmbuild-generic
    labels:
      maintainer: *rpmbuild_email
      vendor: *rpmbuild_vendor
  # Configuration for every dependency RPM.
  rpms:
    CGAL:
      image: &CGAL_image rpmbuild-cgal
      version: &CGAL_version '4.14.3-1'
    FileGDBAPI:
      image: &FileGDBAPI_image rpmbuild-generic
      version: &FileGDBAPI_version '1.5.1-1'
    SFCGAL:
      image: &SFCGAL_image rpmbuild-sfcgal
      version: &SFCGAL_version '1.3.9-1'
    gdal:
      image: &gdal_image rpmbuild-gdal
      version: &gdal_version '3.2.1-1'
    geos:
      image: &geos_image rpmbuild-geos
      version: &geos_version '3.9.1-1'
    gpsbabel:
      image: &gpsbabel_image rpmbuild-gpsbabel
      version: &gpsbabel_version '1.7.0-1'
    libgeotiff:
      image: &libgeotiff_image rpmbuild-libgeotiff
      version: &libgeotiff_version '1.6.0-1'
    libkml:
      image: &libkml_image rpmbuild-libkml
      version: &libkml_version '1.3.0-1'
    osmosis:
      image: &osmosis_image rpmbuild-generic
      version: &osmosis_version '0.48.3-1'
    sbt:
      image: &sbt_image rpmbuild-generic
      version: &sbt_version '1.4.7-1'
    proj:
      image: &proj_image rpmbuild-proj
      version: &proj_version '7.2.1-1'
    proj6:
      image: &proj6_image rpmbuild-proj
      version: &proj6_version '6.3.2-1'
    protozero:
      image: &protozero_image rpmbuild-protozero
      version: &protozero_version '1.7.0-1'
    sqlite:
      image: &sqlite_image rpmbuild-sqlite
      version: &sqlite_version '3.34.1-1'
  service_volumes: &service_volumes
    - "./RPMS:/rpmbuild/RPMS:rw"
    - "./SOURCES:/rpmbuild/SOURCES:rw"
    - "./SPECS:/rpmbuild/SPECS:ro"
    - "./scripts:/rpmbuild/scripts:ro"
  service_defaults: &service_defaults
    command: 'tail -f /dev/null'
    init: true
    volumes: *service_volumes

services:
  rpmbuild:
    build:
      context: .
      dockerfile: docker/Dockerfile.rpmbuild
      args:
        <<: *rpmbuild_base_args
      labels:
        maintainer: *rpmbuild_email
        vendor: *rpmbuild_vendor
    command: 'tail -f /dev/null'
    init: true
    user: nobody
  rpmbuild-generic:
    <<: *service_defaults
    depends_on:
      - rpmbuild
    build:
      <<: *build_defaults
      args:
        rpmbuild_channel: *rpmbuild_channel
  rpmbuild-cgal:
    <<: *service_defaults
    depends_on:
      - rpmbuild-generic
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_CGAL_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
  rpmbuild-gdal:
    <<: *service_defaults
    depends_on:
      - rpmbuild-pgdg
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_GDAL_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
        cgal_version: *CGAL_version
        filegdbapi_version: *FileGDBAPI_version
        gpsbabel_version: *gpsbabel_version
        geos_version: *geos_version
        libgeotiff_version: *libgeotiff_version
        libkml_version: *libkml_version
        proj_version: *proj_version
        sfcgal_version: *SFCGAL_version
        sqlite_version: *sqlite_version
      dockerfile: docker/Dockerfile.rpmbuild-gdal
  rpmbuild-geos:
    <<: *service_defaults
    depends_on:
      - rpmbuild-generic
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_GEOS_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
  rpmbuild-gpsbabel:
    <<: *service_defaults
    depends_on:
      - rpmbuild-generic
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_GPSBABEL_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
  rpmbuild-sqlite:
    <<: *service_defaults
    depends_on:
      - rpmbuild-generic
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_SQLITE_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
  rpmbuild-proj:
    <<: *service_defaults
    depends_on:
      - rpmbuild-sqlite
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_PROJ_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
        sqlite_version: *sqlite_version
      dockerfile: docker/Dockerfile.rpmbuild-proj
  rpmbuild-libgeotiff:
    <<: *service_defaults
    depends_on:
      - rpmbuild-proj
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_LIBGEOTIFF_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
        proj_version: *proj_version
      dockerfile: docker/Dockerfile.rpmbuild-libgeotiff
  rpmbuild-libkml:
    <<: *service_defaults
    depends_on:
      - rpmbuild-generic
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_LIBKML_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
  rpmbuild-pgdg:
    <<: *service_defaults
    depends_on:
      - rpmbuild
    build:
      <<: *build_defaults
      args:
        postgres_version: *postgres_version
        rpmbuild_channel: *rpmbuild_channel
      dockerfile: docker/Dockerfile.rpmbuild-pgdg
  rpmbuild-protozero:
    <<: *service_defaults
    depends_on:
      - rpmbuild-generic
    build:
      <<: *build_defaults
      args:
        packages: "${RPMBUILD_PROTOZERO_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
  rpmbuild-sfcgal:
    <<: *service_defaults
    depends_on:
      - rpmbuild-cgal
    build:
      <<: *build_defaults
      args:
        cgal_version: *CGAL_version
        packages: "${RPMBUILD_SFCGAL_PACKAGES}"
        rpmbuild_channel: *rpmbuild_channel
      dockerfile: docker/Dockerfile.rpmbuild-sfcgal
