---
name: Upload repository

inputs:
  aws_access_key_id:
    description: AWS_ACCESS_KEY_ID
    required: true
  aws_secret_access_key:
    description: AWS_SECRET_ACCESS_KEY
    required: true
  el_version:
    description: The EL version ('el_version' + '/' is prepended to 'repo_dirname')
    required: true
  repo_dirname:
    default: ${{ github.ref_name }}
    description: Repository directory name
    required: false
  repo_parent_dir:
    default: /tmp/repos
    description: Repository parent directory
    required: false
  s3_bucket:
    default: geoint-deps
    description: S3 bucket name
    required: false

runs:
  using: composite

  steps:
    - name: Install AWS CLI
      run: pip3 install --user awscli
      shell: bash --noprofile --norc -euxo pipefail {0}

    - name: Upload repository to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        REPO_DIR: ${{ inputs.repo_parent_dir }}/${{ inputs.el_version }}/${{ inputs.repo_dirname }}
        S3_URI: s3://${{ inputs.s3_bucket }}/${{ inputs.el_version }}/${{ inputs.repo_dirname }}
      run: ~/.local/bin/aws s3 sync ${REPO_DIR} ${S3_URI} --delete --no-progress
      shell: bash --noprofile --norc -euxo pipefail {0}
