---
name: Upload repository

inputs:
  aws_access_key_id:
    description: AWS_ACCESS_KEY_ID
    required: true
  aws_secret_access_key:
    description: AWS_SECRET_ACCESS_KEY
    required: true
  repo_dirname:
    default: ${{ github.ref_name }}
    description: Repository directory name
    required: false
  repo_parent_dir:
    default: /tmp/repos
    description: Repository parent directory
    required: false
  s3_bucket:
    default: geoint-apps
    description: S3 bucket name
    required: false

runs:
  using: composite

  steps:
    - name: Upload repository to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
      run: |
        yum -q -y install python3-pip
        pip3 install awscli

        REPO_DIR=${{ inputs.repo_parent_dir }}/${{ inputs.repo_dirname }}
        S3_URI=s3://${{ inputs.s3_bucket }}/${{ inputs.repo_dirname }}
        aws s3 sync --delete --no-progress \
          ${REPO_DIR} ${S3_URI}
      shell: bash --noprofile --norc -euxo pipefail {0}
