ARG rpmbuild_channel
ARG rpmbuild_image=rpmbuild-generic
FROM deps-${rpmbuild_channel}_${rpmbuild_image}:latest
ARG packages
ARG python3_packages
ARG libosmium_version
ARG protozero_version

USER root

COPY RPMS/noarch/libosmium-devel-${libosmium_version}${RPMBUILD_DIST}.noarch.rpm \
     RPMS/noarch/protozero-devel-${protozero_version}${RPMBUILD_DIST}.noarch.rpm \
     /tmp/

SHELL ["/bin/bash", "-c"]
RUN --mount=type=cache,target=/var/cache/yum \
    yum install -y \
    /tmp/libosmium-devel-${libosmium_version}${RPMBUILD_DIST}.noarch.rpm \
    /tmp/protozero-devel-${protozero_version}${RPMBUILD_DIST}.noarch.rpm \
    && \
    rm -f /tmp/*.rpm && \
    if [ -n "${packages}" ] ; then yum -q -y install ${packages}; fi && \
    if [ -n "${python3_packages}" ] ; then pip3 install --disable-pip-version-check ${python3_packages}; fi

# Use unprivileged RPM build user and work directory by default.
USER ${RPMBUILD_USER}
WORKDIR ${RPMBUILD_HOME}
