---
name: Delete package

inputs:
  el_version:
    description: The EL version ('el_version' + '%2F' is prepended to 'package_name')
    required: true
  package_name:
    description: The name of the package
    required: true
  package_type:
    default: container
    description: The type of supported package
    required: false
  token:
    default: ${{ github.token }}
    description: The token
    required: false
  token_type:
    default: bearer
    description: The token type
    required: false

runs:
  using: composite

  steps:
    - name: Delete the `${{ inputs.package_name }}` ${{ inputs.package_type }} package
      run: |
        PKG_PREFIX="$(echo '${{ github.repository }}' | sed 's#^${{ github.repository_owner }}/##')%2F"
        PKG_PATH="${PKG_PREFIX}${{ inputs.el_version }}%2F${{ inputs.package_name }}"
        URL_PATH="/orgs/${{ github.repository_owner }}/packages/${{ inputs.package_type }}/${PKG_PATH}"

        curl \
          --header "Accept: application/vnd.github.v3+json" \
          --header "Authorization: ${{ inputs.token_type }} ${{ inputs.token }}" \
          --request DELETE \
          --silent \
          --url "https://api.github.com${URL_PATH}"
      shell: bash --noprofile --norc -euxo pipefail {0}
