---
name: CI (EL9)

on:
  - push

env:
  DOCKER_BUILDKIT: 1
  IMAGE_PREFIX: ghcr.io/${{ github.repository }}/el9/
  PACKAGE_PREFIX: geoint-deps%2Fel9%2F

jobs:
  build-images:
    name: Build `${{ matrix.image }}` Image
    runs-on: ubuntu-latest

    strategy:
      # Uncomment the following lines in order to build & push base images
      max-parallel: 1
      matrix:
        image:
          - rpmbuild
          - rpmbuild-fonts
          - rpmbuild-generic
          - rpmbuild-pgdg

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete old images
        uses: ./.github/actions/github-api/delete-package
        with:
          package_name: ${{ env.PACKAGE_PREFIX }}${{ matrix.image }}
          token: ${{ secrets.PKG_DELETE_TOKEN }}
          token_type: token

      - name: Build `${{ matrix.image }}` Image
        uses: ./.github/actions/build
        with:
          image_prefix: ${{ env.IMAGE_PREFIX }}
          make_target: ${{ matrix.image }}
          push_image: true


  build-rpms-1:
    name: Build `${{ matrix.rpm }}` RPM(s)
    needs: build-images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rpm:
          - arpack
          - CGAL
          - dumb-init
          - FileGDBAPI
          - g2clib
          - geos
          - google-noto-fonts-extra
          - gpsbabel
          - hanazono-fonts
          - iniparser
          - journald-cloudwatch-logs
          - libgta
          - libosmium
          - libpqxx
          - mapnik
          - ogdi
          - openstreetmap-carto
          - osm2pgsql
          - osmctools
          - osmdbt
          - osmium-tool
          - osmosis
          - passenger
          - postgis
          - proj
          - protozero
          - pyosmium
          - python3-mapnik
          - rack
          - rubygem-libxml-ruby
          - sbt
          - sqlite-pcre
          - uriparser

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build `${{ matrix.rpm }}` RPM(s)
        uses: ./.github/actions/build
        with:
          image_prefix: ${{ env.IMAGE_PREFIX }}
          make_target: ${{ matrix.rpm }}


  build-rpms-2:
    name: Build `${{ matrix.rpm }}` RPM(s)
    needs: build-rpms-1
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rpm:
          - armadillo
          - libgeotiff
          - libkml
          - SFCGAL

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build `${{ matrix.rpm }}` RPM(s)
        uses: ./.github/actions/build
        with:
          image_prefix: ${{ env.IMAGE_PREFIX }}
          download_rpms: true
          make_target: ${{ matrix.rpm }}


  build-rpms-3:
    name: Build `${{ matrix.rpm }}` RPM(s)
    needs: build-rpms-2
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rpm:
          - gdal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build `${{ matrix.rpm }}` RPM(s)
        uses: ./.github/actions/build
        with:
          image_prefix: ${{ env.IMAGE_PREFIX }}
          download_rpms: true
          make_target: ${{ matrix.rpm }}
